version: '3.4'
name: apiprodutorruralmonitoramento
services:
  produtorruralmonitoramento.api:
    image: ${DOCKER_REGISTRY-}produtorruralmonitoramentoapi
    container_name: apiprodutorruralmonitoramento
    build:
      context: .
      dockerfile: src/ProdutorRuralMonitoramento.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "5003:80"
    networks:
      - agro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  agro-network:
    external: true